# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# github actions 中文文档 https://docs.github.com/cn/actions/getting-started-with-github-actions

name: deploy for qiankun

on:
    push:
        branches:
            - 'qiankun' # 只针对 dev 分支
        paths:
            - '.github/workflows/*'
            - 'src/**'
            - 'Dockerfile'
            - 'docker-compose.yml'
            - 'bin/*'
            - 'docs/*'
            - 'config/*'
            - 'subApps/**'

jobs:
    deploy-dev:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: set ssh key # 临时设置 ssh key
              run: |
                  mkdir -p ~/.ssh/
                  echo "${{secrets.MODERATE_SSH_KEY_PC}}" > ~/.ssh/id_rsa # secret 在这里配置 https://github.com/imooc-lego/biz-editor-server/settings/secrets
                  chmod 600 ~/.ssh/id_rsa
                  ssh-keyscan "49.233.107.254" >> ~/.ssh/known_hosts
            - name: deploy # 部署
              run: |
                  ssh play@49.233.107.254 "
                    cd /home/play/projects/moderate-react-template;
                    git checkout qiankun
                    git pull;
                    yarn;
                    yarn build

                    "
            - name: delete ssh key # 删除 ssh key
              run: rm -rf ~/.ssh/id_rsa
